<?php

namespace AppBundle\Repository;

/**
 * ClothRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClothRepository extends \Doctrine\ORM\EntityRepository
{
    public function tshirtActionByTemp($season, $temperature)
    {
        return $this->getEntityManager()
        ->createQuery(
            "SELECT c
            FROM AppBundle:Cloth c
            WHERE c.season = :season
            AND c.part = '4'
            AND c.temperature > :temperature"

            )->setParameter('season' , $season)
            ->setParameter('temperature' , $temperature)


            ->getResult();

    }
    public function uptActionByTemp($season, $temperature)
    {
        return $this->getEntityManager()
        ->createQuery(
            "SELECT c
            FROM AppBundle:Cloth c
            WHERE c.season = :season
            AND c.part = '5'
            AND c.temperature > :temperature"

            )->setParameter('season' , $season)
            ->setParameter('temperature' , $temperature)


            ->getResult();

    }
    public function downtActionByTemp($season, $temperature)
    {
        return $this->getEntityManager()
        ->createQuery(
            "SELECT c
            FROM AppBundle:Cloth c
            WHERE c.season = :season
            AND c.part = '3'
            AND c.temperature > :temperature"

            )->setParameter('season' , $season)
            ->setParameter('temperature' , $temperature)


            ->getResult();

    }
}
