<?php

namespace AppBundle\Repository;

/**
 * OutfitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OutfitRepository extends \Doctrine\ORM\EntityRepository
{
}
