<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBb0y06v\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBb0y06v/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBb0y06v.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBb0y06v\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerBb0y06v\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Bb0y06v',
    'container.build_id' => 'fd6063b2',
    'container.build_time' => 1529412198,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerBb0y06v');
